# Generated by Django 5.2.6 on 2025-09-25 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_rename_accounts_account_and_more'),
        ('accounting_logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account_Logs',
            new_name='Account_Log',
        ),
        migrations.RenameModel(
            old_name='Transaction_Logs',
            new_name='Transaction_Log',
        ),
        migrations.RenameModel(
            old_name='User_Logs',
            new_name='User_Log',
        ),
    ]
