# Generated by Django 5.2.6 on 2025-09-26 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='accountlog',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='accountlog',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_logs', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='accountlog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='accounting.transaction'),
        ),
        migrations.AddField(
            model_name='userlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accountlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_logs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountlog',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountlog',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='accountlog',
            index=models.Index(fields=['account'], name='logs_accoun_account_ef4f61_idx'),
        ),
        migrations.AddIndex(
            model_name='accountlog',
            index=models.Index(fields=['created_by'], name='logs_accoun_created_8385cf_idx'),
        ),
        migrations.AddIndex(
            model_name='accountlog',
            index=models.Index(fields=['created_at'], name='logs_accoun_created_166825_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['transaction'], name='logs_transa_transac_c22b22_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['account'], name='logs_transa_account_f50b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['created_by'], name='logs_transa_created_2b009a_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['created_at'], name='logs_transa_created_4a385b_idx'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['user'], name='logs_userlo_user_id_ddcf3c_idx'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['changed_by'], name='logs_userlo_changed_46be69_idx'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['created_at'], name='logs_userlo_created_44fa31_idx'),
        ),
    ]
