# Generated by Django 5.2.6 on 2025-10-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=6),
        ),
    ]
