# Generated by Django 5.2.6 on 2025-10-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_users_sex'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactionline',
            name='debit_or_credit_nonzero',
        ),
        migrations.AddConstraint(
            model_name='transactionline',
            constraint=models.CheckConstraint(condition=models.Q(('debit_amount', 0), ('credit_amount', 0), _negated=True), name='debit_or_credit_nonzero'),
        ),
    ]
