# Generated by Django 5.2.6 on 2025-09-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_monthly_balance_balance_sheet_transactions_and_more'),
        ('accounting_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
        migrations.RenameModel(
            old_name='Transaction_Lines',
            new_name='Transaction_Line',
        ),
    ]
