# Generated by Django 5.2.6 on 2025-09-26 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_rename_accounts_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date']},
        ),
        migrations.RemoveField(
            model_name='balance_sheet',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='transaction_line',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='transaction_line',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='balance_sheet',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_sheets', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction_line',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_lines', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='transaction_line',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_lines', to='accounting.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_line',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='accounting__transac_0accd6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_by'], name='accounting__created_d33392_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction_line',
            constraint=models.CheckConstraint(condition=models.Q(('credit_amount', 0), ('debit_amount', 0)), name='debit_or_credit_nonzero'),
        ),
    ]
